name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm i

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Unit Tests with Coverage
        run: pnpm run test:unit -- --coverage.enabled --coverage.reporter=json-summary

      - name: Run E2E Tests
        run: pnpm run test:e2e

      - name: Generate Lines Coverage Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        with:
          result-type: lines
          summary-path: coverage/coverage-summary.json
          badge-path: lines-badge.svg
          badge-text: 'Lines Coverage'
          vitest-config-path: vite.config.ts
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: https://gist.github.com/Kyran121/3297558a26163acee4e360d24d9ea776

      - name: Generate Branches Coverage Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        with:
          result-type: branches
          summary-path: coverage/coverage-summary.json
          badge-path: branches-badge.svg
          badge-text: 'Branches Coverage'
          vitest-config-path: vite.config.ts
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: https://gist.github.com/Kyran121/3297558a26163acee4e360d24d9ea776

      - name: Upload Lines Coverage Badge Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge-lines
          path: coverage/lines-badge.svg

      - name: Upload Branches Coverage Badge Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge-branches
          path: coverage/branches-badge.svg
